// nfm/nfm/message.h -- message #
// Copyright(c) KAMINA Jiro 2006-2007.  All rights reserved.
// $Header$

#if !defined(MESSAGE_H_)
#define MESSAGE_H_

enum fm_msg {
	MSG_DIRECT = -1,
	MSG_MSGSTART = 0,
	MSG_COPYRIGHT,
	MSG_START,
	MSG_ASKSOLVE,
	MSG_ASKCONTINUE,
	MSG_INTERRUPT,
	MSG_NOTMATE,
	MSG_FIGTITLE,
	MSG_ANOTHERMATE1ST,
	MSG_ANOTHERMATE,
	MSG_LOOSEMATE1ST,
	MSG_LOOSEMATE,
	MSG_SHORTMATE,
	MSG_SINFO,
	MSG_HIHASH,
	MSG_HIHASHTEST,
	MSG_HIHASHCOMP,
	MSG_YOHASH,
	MSG_YOHASHTEST,
	MSG_YOHASHCOMP,
	MSG_ERR_MEMALLOC,
	MSG_ERR_FILEOPEN,
	MSG_ERR_OPTARG,
	MSG_ERR_INDATA,
	MSG_ERR_GIVENMATEPATH,
	MSG_ERR_BOARDNOMORE,
	MSG_ERR_BOARDOVER,
	MSG_ERR_MSEQNOMORE,
	MSG_ERR_MSEQOVER,
	MSG_ADDBOARD,
	MSG_ADDMSEQ,
	MSG_FREEMSEQ,
	MSG_TOTALPHISMEM,
	MSG_AVAILPHISMEM,
	MSG_TOTALVIRTMEM,
	MSG_AVAILVIRTMEM,
	MSG_PHASECOUNTHEAD,
	MSG_PHASECOUNTLINE,
	MSG_MEGABYTES,
	MSG_STARTREUSEMSEQ,
	MSG_REUSEMSEQ,
	MSG_MSGEND
};

enum fm_str {
	STR_STRSTART = 0,
	STR_ELAPSE_S,
	STR_ELAPSE_MS,
	STR_ELAPSE_HMS,
	STR_PHASES,
	STR_DEPTH,
	STR_LASTDEPTH,
	STR_TERMINATE,
	STR_INTERRUPT,
	STR_HELP_MATE,
	STR_HELP_MATE_TFIG,
	STR_HELP_MATE_TFIG_YO1ST,
	STR_HELP_SELFMATE,
	STR_HELP_SELFMATE_TFIG,
	STR_HELP_SELFMATE_TFIG_YO1ST,
	STR_SERIES_HELP_MATE,
	STR_SERIES_MATE,
	STR_HELP_TARGETFIG,
	STR_COND_PWC,
	STR_COND_NOPROM,
	STR_COND_NOPROM_E,
	STR_FILENUM,
	STR_MATE,
	STR_MATE_SH,
	STR_PCLEFT,
	STR_JOIN,
	STR_MATE_DEPTH,
	STR_MATE_DEPTH_SH,
	STR_HAND,
	STR_NOTHING,
	STR_CAPTIT,
	STR_PLACE,
	STR_PROMOTE,
	STR_RAW,
	STR_NOTPROMOTE,
	STR_RIGHT,
	STR_LEFT,
	STR_UP,
	STR_DOWN,
	STR_SIDE,
	STR_JUMP,
	STR_STRAIGHT,
	STR_GO,
	STR_SAMEPHASE,
	STR_LEFTQUOTE,
	STR_RIGHTQUOTE,
	STR_FROM,
	STR_TO,
	STR_STARTFIG,
	STR_ENDFIG,
	STR_MATEFIG,
	STR_TARGETFIG,
	STR_GET_RULE_AND_DEPTH,
	STR_GET_PHASE_DATA,
	STR_GET_PHASE,
	STR_GET_TARGET_PHASE,
	STR_GET_EXTRAPC,
	STR_GET_GIVENMATEPATH,
	STR_ERR_GIVENMATEPATH,
	STR_ERR_GIVENMATEPATH_PC,
	STR_ERR_GIVENMATEPATH_FROM,
	STR_ERR_GIVENMATEPATH_TO,
	STR_ERR_GIVENMATEPATH_CAPT,
	STR_ERR_GIVENMATEPATH_REBORN,
	STR_ERR_GIVENMATEPATH_PROMPOS,
	STR_ERR_GIVENMATEPATH_PROMPC,
	STR_ERR_GIVENMATEPATH_MOVE,
	STR_ERR_GIVENMATEPATH_PHASE,
	STR_SECT_PROBLEM,
	STR_SECT_PROBLEM_E,
	STR_SECT_END,
	STR_SECT_END_E,
	STR_STREND
};

// msg.c
extern const char *msg[];
extern const char *str[];
extern const char **indata_pc[17];
extern const char *graph_pc[];
extern const char *graph_mv_pc[];
extern const char *graph_hi_pc[];
extern const char *graph_yo_pc[];
extern const char *graph_ex_pc[];
extern const char *file_num[];
extern const char *rank_num[];
extern const char *board_rank_num[];

#endif // !MESSAGE_H_

